name: Main Workflow

on:
  push:
    branches:
      - main

env: 
  REGISTRY: ghcr.io
  IMAGE_NAME: arq-soft-ii-app/api-gateway:${GITHUB_REF##*/}

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and Publish
      run: | 
        docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
